export default {
  testRunner: "vitest",
  vitest: { configFile: "vitest.config.ts" },
  mutate: [
    "lib/data.ts",
    "app/api/auth/signup/route.ts",
    "app/api/dashboard/route.ts",
    "app/api/invest/route.ts",
    "app/api/sell/route.ts",
    "app/api/wallet/route.ts",
    "app/api/owner/properties/route.ts",
    "components/InvestModal.tsx",
    "components/SellModal.tsx",
    "components/Navbar.tsx",
    "components/OwnerSidebar.tsx",
    "components/DashboardSidebar.tsx",
    "components/PropertyListingCard.tsx",
  ],
  reporters: ["html", "clear-text", "progress"],
  htmlReporter: { fileName: "reports/mutation/index.html" },
  thresholds: { high: 80, low: 50, break: 50 },
  timeoutMS: 10000,
  timeoutFactor: 2.0,
  concurrency: 2,
  incremental: true,
  incrementalFile: ".stryker-tmp/incremental.json",
  tempDirName: ".stryker-tmp",
  ignorePatterns: [
    ".next",
    "node_modules",
    "coverage",
    "reports",
    "prisma",
    ".stryker-tmp",
  ],
};
